[package]
name = "bulletproof"
version = "1.1.6"
authors = [
    "Omer Shlomovits <omer@kzencorp.com>",
    "Suyash Bagad <suyashnbagad1997@gmail.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
itertools = "0.7.8"
serde = "1.0"
serde_derive = "1.0"
curv = { git = "https://github.com/sgx-test/curv-sgx", branch = "0.7.0-generic-update", version = "0.7", default-features = false }

[dev-dependencies]
criterion = "0.2"

[features]
default = ["curv/rust-gmp-kzen"]

[[bench]]
name = "range_proof"
path = "benches/range_proof.rs"
harness = false
